services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: cbm_app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    depends_on:
      - postgres
      - redis
    networks:
      - cbm_network

  nginx:
    image: nginx:alpine
    container_name: cbm_nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - cbm_network

  postgres:
    image: postgres:15
    container_name: cbm_postgres
    restart: always
    environment:
      POSTGRES_DB: cbm
      POSTGRES_USER: cbm
      POSTGRES_PASSWORD: cbm
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - cbm_network

  redis:
    image: redis:7
    container_name: cbm_redis
    ports:
      - "6379:6379"
    networks:
      - cbm_network

  frontend:
    image: node:20
    container_name: cbm_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    networks:
      - cbm_network

volumes:
  pgdata:

networks:
  cbm_network:
